# Generated by Django 2.2 on 2020-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='knowledge',
            field=models.CharField(default=99, max_length=100),
            preserve_default=False,
        ),
    ]
