# Generated by Django 2.2 on 2020-02-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_post_knowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='knowledge',
        ),
    ]
