# Generated by Django 2.2 on 2020-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_post_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='knowledge',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
